In [2]:
import pandas as pd

In [25]:
#Creates a path to the document
pollution_path="World pollution KPI.csv"

#Transforms the info into a dataframe
pollution_df=pd.read_csv(pollution_path, encoding="utf-8")

In [26]:
pollution_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,46.536809,50.483960,50.653945,50.968831,49.036091,62.080234,62.854857,NaN,NaN
2,Angola,AGO,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.921716,31.800657,33.407050,33.507051,35.331048,35.788469,36.240479,NaN,NaN
3,Albania,ALB,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,15.335690,14.646135,14.562992,15.635917,16.748862,14.736548,14.634008,NaN,NaN
4,Andorra,AND,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,11.115808,11.230666,11.254432,10.942684,10.667695,10.908934,10.879472,NaN,NaN

In [27]:
pollution_df.count()

Country Name      264
Country Code      264
Indicator Name    264
Indicator Code    264
1960                0
1961                0
1962                0
1963                0
1964                0
1965                0
1966                0
1967                0
1968                0
1969                0
1970                0
1971                0
1972                0
1973                0
1974                0
1975                0
1976                0
1977                0
1978                0
1979                0
1980                0
1981                0
1982                0
1983                0
1984                0
1985                0
                 ...
1989                0
1990              240
1991                0
1992                0
1993                0
1994                0
1995              240
1996                0
1997                0
1998                0
1999                0
2000              240
2001                0
2002                0
2003                0
2004                0
2005              240
2006                0
2007                0
2008                0
2009                0
2010              240
2011              240
2012              240
2013              240
2014              240
2015              240
2016              240
2017                0
2018                0
Length: 63, dtype: int64

In [28]:
#Replaces the NaN with 0. In case of being needed, we can delete the null data easily. 
pollution_df=pollution_df.fillna(0)

In [35]:
pollution_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1,Afghanistan,AFG,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,46.536809,50.483960,50.653945,50.968831,49.036091,62.080234,62.854857,0.0,0.0
2,Angola,AGO,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,30.921716,31.800657,33.407050,33.507051,35.331048,35.788469,36.240479,0.0,0.0
3,Albania,ALB,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,15.335690,14.646135,14.562992,15.635917,16.748862,14.736548,14.634008,0.0,0.0
4,Andorra,AND,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,11.115808,11.230666,11.254432,10.942684,10.667695,10.908934,10.879472,0.0,0.0
5,Arab World,ARB,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,63.791725,63.148567,63.801393,63.391541,62.994614,81.936630,83.151463,0.0,0.0
6,United Arab Emirates,ARE,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,72.804855,71.696350,73.529888,69.472695,65.924122,102.926240,105.123736,0.0,0.0
7,Argentina,ARG,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,14.224179,14.061859,14.075854,13.577209,13.643647,14.117203,14.148167,0.0,0.0
8,Armenia,ARM,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,25.720828,25.860902,24.035917,24.665185,25.068702,27.132037,26.972893,0.0,0.0
9,American Samoa,ASM,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.368691,3.255184,3.377271,3.457885,3.634140,3.790379,3.763412,0.0,0.0
10,Antigua and Barbuda,ATG,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,13.374218,13.613442,13.711044,14.014765,13.768418,15.517696,15.685943,0.0,0.0
11,Australia,AUS,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,5.937561,5.880919,5.981776,6.028238,5.933055,6.109838,6.126806,0.0,0.0
12,Austria,AUT,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,15.147755,14.933958,15.247447,15.943622,16.466067,15.032289,14.965188,0.0,0.0
13,Azerbaijan,AZE,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,26.223822,25.228131,24.681045,26.551909,28.368979,32.659225,32.977620,0.0,0.0
14,Burundi,BDI,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,40.180277,44.086442,47.431512,48.139333,47.085069,46.450195,46.282935,0.0,0.0
15,Belgium,BEL,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,16.308207,16.295783,15.881559,15.901439,15.796535,16.019277,16.043432,0.0,0.0
16,Benin,BEN,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,42.479460,45.744417,45.122604,41.325474,38.263049,90.466348,95.960323,0.0,0.0
17,Burkina Faso,BFA,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,60.971364,62.738809,54.945709,49.587730,44.105310,104.894426,110.730802,0.0,0.0
18,Bangladesh,BGD,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,82.404146,82.780242,82.939834,88.526426,87.118535,100.323815,101.017157,0.0,0.0
19,Bulgaria,BGR,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,26.862789,26.974504,25.728303,26.717877,27.559881,25.679603,25.646688,0.0,0.0
20,Bahrain,BHR,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,66.810304,63.312289,67.576134,66.620464,60.356613,79.127747,79.691000,0.0,0.0
21,"Bahamas, The",BHS,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,12.312657,12.766803,13.351623,13.743270,13.644731,12.933554,12.791142,0.0,0.0
22,Bosnia and Herzegovina,BIH,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,38.115526,37.445735,38.036173,41.611566,44.189949,39.532926,39.271781,0.0,0.0
23,Belarus,BLR,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,20.213096,19.697793,18.511933,19.515463,19.972374,19.744525,19.798731,0.0,0.0
24,Belize,BLZ,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,21.020076,21.733952,25.367879,24.424743,25.468381,20.368448,20.181599,0.0,0.0
25,Bermuda,BMU,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.451374,9.605679,9.558182,9.103641,9.089119,10.328921,10.474018,0.0,0.0
26,Bolivia,BOL,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,28.619321,30.323356,27.017189,27.794154,28.384249,22.267582,22.042692,0.0,0.0
27,Brazil,BRA,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,10.964792,11.479129,11.211681,11.439267,11.319054,12.581153,12.652859,0.0,0.0
28,Barbados,BRB,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,14.769710,14.882038,15.153770,15.059940,15.204289,18.149225,18.414813,0.0,0.0
29,Brunei Darussalam,BRN,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,6.380135,6.228895,6.210098,6.176910,5.656721,6.372126,6.429309,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,17.245196,17.882188,18.269207,18.292409,17.893656,17.742832,17.777490,0.0,0.0
235,Timor-Leste,TLS,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,19.159694,18.608837,18.776054,18.931253,18.768396,17.067330,17.000534,0.0,0.0
236,Middle East & North Africa (IDA & IBRD countries),TMN,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,56.825398,55.584000,55.219491,56.169657,56.867850,67.984537,68.664370,0.0,0.0
237,Tonga,TON,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.903498,3.868612,3.954435,3.983513,3.978564,4.016893,3.993594,0.0,0.0
238,South Asia (IDA & IBRD),TSA,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,65.097419,64.887621,66.556812,69.442314,71.282729,76.972526,77.288748,0.0,0.0
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,39.682624,41.547364,41.200180,39.459228,37.585535,64.620651,67.128496,0.0,0.0
240,Trinidad and Tobago,TTO,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,12.256323,12.306387,12.558981,13.482248,13.673345,16.608408,16.812273,0.0,0.0
241,Tunisia,TUN,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,35.477905,34.079991,33.545001,35.873537,39.874589,35.874271,35.565679,0.0,0.0
242,Turkey,TUR,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,32.585325,32.145702,30.322359,33.057693,34.677269,37.157526,37.253918,0.0,0.0
243,Tuvalu,TUV,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
244,Tanzania,TZA,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,20.967769,22.284692,23.473103,23.723987,23.489644,22.386705,22.349307,0.0,0.0
245,Uganda,UGA,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,52.900973,58.361328,62.146828,62.338002,61.386417,72.756373,73.511723,0.0,0.0
246,Ukraine,UKR,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,19.260641,18.877343,18.619552,18.554945,18.772273,19.219889,19.206062,0.0,0.0
247,Upper middle income,UMC,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,42.766701,42.098696,42.078949,41.833019,42.341802,42.067876,42.066308,0.0,0.0
248,Uruguay,URY,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,11.802362,11.705169,11.758868,11.540030,11.613132,11.541681,11.523398,0.0,0.0
249,United States,USA,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,8.616733,8.649967,8.677356,8.531050,8.501964,9.166296,9.196934,0.0,0.0
250,Uzbekistan,UZB,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,37.182382,36.033570,37.333429,36.985751,38.632293,46.213010,46.691076,0.0,0.0
251,St. Vincent and the Grenadines,VCT,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,13.873851,13.556230,14.054468,14.301171,14.166098,16.764536,17.374320,0.0,0.0
252,"Venezuela, RB",VEN,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,22.703424,24.083353,23.795019,24.765075,23.730969,26.066509,26.331181,0.0,0.0
253,British Virgin Islands,VGB,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
254,Virgin Islands (U.S.),VIR,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,15.337558,14.197201,16.641335,16.683942,14.832249,17.645544,18.381432,0.0,0.0
255,Vietnam,VNM,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,26.760713,27.208112,27.392973,27.815889,27.976149,26.396944,26.285906,0.0,0.0
256,Vanuatu,VUT,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,7.686920,7.446673,7.606976,8.263678,7.985840,8.773083,8.848735,0.0,0.0
257,World,WLD,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,41.858235,41.845011,42.324852,42.879413,43.340166,49.104505,49.673465,0.0,0.0
258,Samoa,WSM,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,3.432087,3.326990,3.412159,3.535518,3.674938,3.851702,3.857073,0.0,0.0
259,Kosovo,XKX,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
260,"Yemen, Rep.",YEM,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,50.528506,55.268507,62.438980,59.399450,55.658510,71.706947,72.553865,0.0,0.0
261,South Africa,ZAF,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,29.751642,29.439874,29.172852,29.115314,29.454797,35.522286,35.912477,0.0,0.0
262,Zambia,ZMB,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,26.427642,27.229630,27.804752,27.650733,27.109114,30.402645,30.550295,0.0,0.0
263,Zimbabwe,ZWE,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,22.480427,23.397666,23.359478,23.448376,23.072327,24.371786,24.513035,0.0,0.0

In [71]:
#DataFrame with just our assigned standards.
developed= pollution_df[pollution_df['Country Name'].isin([ 'France','Japan', 'United Kingdom'])]
developed

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
75,France,FRA,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,12.244528,12.212267,12.262438,12.292927,12.333720,11.891143,11.869338,0.0,0.0
79,United Kingdom,GBR,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,11.812791,11.841180,12.058129,12.033986,12.100091,11.546478,11.520287,0.0,0.0
117,Japan,JPN,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,12.339645,11.787693,11.973951,12.401346,12.882702,13.148846,13.158396,0.0,0.0

In [72]:
developing= pollution_df[pollution_df['Country Name'].isin([ 'Turkey','Mexico', 'Thailand'])]
developing

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
152,Mexico,MEX,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,20.244983,20.548946,21.611224,20.753771,20.458205,18.908099,18.829104,0.0,0.0
231,Thailand,THA,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,22.488404,22.974655,23.905890,25.078727,25.516179,23.276532,23.172590,0.0,0.0
242,Turkey,TUR,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,32.585325,32.145702,30.322359,33.057693,34.677269,37.157526,37.253918,0.0,0.0

In [78]:
underdeveloped=pollution_df[pollution_df['Country Name'].isin(['Philippines','Egypt, Arab Rep.', "Vietnam"])]
underdeveloped

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
65,"Egypt, Arab Rep.",EGY,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,90.392779,89.034874,88.486924,95.096404,99.342872,124.875127,126.028231,0.0,0.0
185,Philippines,PHL,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,23.577928,23.613135,23.287364,23.970694,23.547761,23.227255,23.213494,0.0,0.0
255,Vietnam,VNM,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,26.760713,27.208112,27.392973,27.815889,27.976149,26.396944,26.285906,0.0,0.0

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
65,"Egypt, Arab Rep.",EGY,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,90.392779,89.034874,88.486924,95.096404,99.342872,124.875127,126.028231,0.0,0.0
185,Philippines,PHL,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,23.577928,23.613135,23.287364,23.970694,23.547761,23.227255,23.213494,0.0,0.0
255,Vietnam,VNM,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,26.760713,27.208112,27.392973,27.815889,27.976149,26.396944,26.285906,0.0,0.0